services:
  face-training-service:
    build: .
    container_name: face-training-service
    ports:
      - "5001:5000"
    volumes:
      - ./training_data:/app/training_data
      - ./models:/app/models
      - ./uploads:/app/uploads
    devices:
      - /dev/video0:/dev/video0
    privileged: true
    environment:
      - FLASK_ENV=production
      - PYTHONUNBUFFERED=1
      - DISPLAY=${DISPLAY}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  training_data:
  models:
  uploads:
